# This is a basic workflow that is manually triggered

name: Deploy bop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create-artifact:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Set up Java version
      run: echo "Setting up java-version 11"
    - name: Build with Maven
      run: echo "mvn clean install"
    - name: Set up Node version
      run: echo "Set up Node version"
    - name: Install dependencies
      run: echo "npm install"
    - name: Build Angular
      if: false
      run: echo "npm run build -- --prod"
      
  deploy-dev:
    if: ${{ 'dev' == github.event.inputs.project }}
    needs: [create-artifact]
    environment: dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Deploy server to Azure Web App DEV
      run: echo "Deploy server to Azure Web App"
    - name: Deploy ui to Azure Web App DEV
      run: echo "Deploy ui to Azure Web App"

  deploy-prod:
    if: ${{ 'prod' == github.event.inputs.project }}
    needs: [create-artifact]
    environment: prod
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    # Runs a single command using the runners shell
    - name: Deploy server to Azure Web App PROD
      run: echo "Deploy server to Azure Web App"
    - name: Deploy ui to Azure Web App PROD
      run: echo "Deploy ui to Azure Web App"
