# This is a basic workflow that is manually triggered

name: Deploy bop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a three jobs: create-artifact, deploy-dev and deploy-prod
  build-server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build with Maven
      working-directory: ./server
      run: mvn clean install

  build-ui:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: Set up Node version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build with Maven
      if: false
      working-directory: ./server
      run: mvn clean install
    - name: Install dependencies
      if: false
      working-directory: ./ui/bop-ui
      run: npm install

    - name: Build Angular
      if: false
      working-directory: ./ui/bop-ui
      run: npm run build -- --prod
    
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.environment }}"
      
  deploy-dev:
    if: ${{ 'dev' == github.event.inputs.environment }}
    needs: [build-server,build-ui]
    environment: dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Deploy server to Azure Web App DEV
      run: echo "Deploy server to Azure Web App"
    - name: Deploy ui to Azure Web App DEV
      run: echo "Deploy ui to Azure Web App"

  deploy-prod:
    if: ${{ 'prod' == github.event.inputs.environment }}
    needs: [build-server,build-ui]
    environment: prod
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    # Runs a single command using the runners shell
    - name: Deploy server to Azure Web App PROD
      run: echo "Deploy server to Azure Web App"
    - name: Deploy ui to Azure Web App PROD
      run: echo "Deploy ui to Azure Web App"
